@startuml
hide footbox
skinparam maxMessageSize 90
skinparam sequence {
backgroundColor #3e1404
BorderColor #bb6b24
ArrowColor #964315
}

skinparam Note {
BackgroundColor #bb6b24
BorderColor #6a2b05
}

skinparam participant {
FontName Arial
Style awesome
BorderColor 964315
BackgroundColor bb6b24
}

== Normative Flow ==
Alice -> CoffeePot: Make me Espresso
CoffeePot -> CoffeePot: Making the Espresso
CoffeePot -> AuditRepository: Record successful Espresso brew audit log entry
CoffeePot --> Alice: Success - Espresso is made
== 418 Message Flow ==
Alice -> TeaKettle: Make me Coffee
Alice <-- TeaKettle: Failure - "418 I'm a teapot"
@enduml
