@startuml
Alice -> CoffeePot: Make me Espresso
CoffeePot -> CoffeePot: making the Espresso
CoffeePot -> AuditRepository: Record successful Espresso brew audit log entry
CoffeePot --> Alice: Success - Espresso is made

Alice -> TeaKettle: Make me Coffee
Alice <-- TeaKettle: Failure - "418 I'm a teapot"
@enduml
