# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.uv.hotbeverage
canonical: http://www.fhir.org/guides/hotbeverage
name: HotBeverage
title: "HotBeverage FHIR Implementation Guide"
status: draft
publisher: 
  name: Dave Pyke & John Moehrke
  url: https://www.pyke.ca
  email: david@pyke.ca
contact:
  - name: David Pyke
    telecom:
      - system: email
        value: david@pyke.ca
        use: work
  - name: John Moehrke
    telecom:
      - system: email
        value: JohnMoehrke@gmail.com
        use: work
version: 1.4.2021
license: CC0-1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Informational

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
