# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.uv.HotBeverage
canonical: http://example.org
name: HotBeverage
title: "HotBeverage FHIR Implementation Guide"
status: draft
publisher: 
  name: Dave Pyke & John Moehrke
  url: https://www.pyke.ca
  email: david@pyke.ca
contact:
  - name: David Pyke
    telecom:
      - system: email
        value: david@pyke.ca
        use: work
version: 2021-April-1st
license: CC0-1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Joke

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
