id: fhir.acme.hotbeverage
canonical: http://fhir.org/guides/acme/HotBeverage
name: HotBeverage
title: "HotBeverage FHIR Implementation Guide"
description: Based on IETF [RFC 2324 - Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0)](https://tools.ietf.org/html/rfc2324) and its update, [RFC 7168 - The Hyper Text Coffee Pot Control Protocol for Tea Efflux Appliances (HTCPCP-TEA)](https://tools.ietf.org/html/rfc7168), this resource allows for the fulfillment of a device request for an artfully brewed caffeinated beverage, but coffee shares this quality with many other varied preparations based on the filtration of plant material.  Foremost, among these are the category of brews based on the straining of water through prepared leaves from a tea tree.
status: active
publisher: 
  name: Dave Pyke & John Moehrke
  url: https://github.com/DavidPyke/HotBeverage
  email: david@pyke.ca
contact:
  - name: David Pyke
    telecom:
      - system: email
        value: david@pyke.ca
        use: work
  - name: John Moehrke
    telecom:
      - system: email
        value: JohnMoehrke@gmail.com
        use: work
version: 1.4.2022
license: CC0-1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release 
date: 2022-04-01
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  shownav: 'true'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  propagate-status: 'true'
  
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
