id: fhir.acme.hotbeverage
canonical: http://fhir.org/guides/acme/hotbeverage
name: HotBeverage
title: "HotBeverage FHIR Implementation Guide"
status: active
publisher: 
  name: Dave Pyke & John Moehrke
  url: https://github.com/DavidPyke/HotBeverage
  email: david@pyke.ca
contact:
  - name: David Pyke
    telecom:
      - system: email
        value: david@pyke.ca
        use: work
  - name: John Moehrke
    telecom:
      - system: email
        value: JohnMoehrke@gmail.com
        use: work
version: 1.4.2021
license: CC0-1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release 
date: 2022-04-01
menu:
  Home: index.html
  Artifacts: artifacts.html
